import { defineQuiz } from "@/features/quiz/definition";

export const arrayQuiz = defineQuiz({
  moduleSlug: "array",
  title: "Quiz Akhir Array",
  questions: [
    {
      id: "array-zero-based-index",
      topicSlug: "indexing",
      prompt: "Pada Array zero-based, index elemen pertama adalah...",
      options: [
        { id: "zero", label: "0" },
        { id: "one", label: "1" },
        { id: "minus-one", label: "-1" },
        { id: "size", label: "size" },
      ],
      correctOptionId: "zero",
      explanation: "Array zero-based menempatkan elemen pertama pada index 0.",
    },
    {
      id: "array-direct-access",
      topicSlug: "access",
      prompt: "Mengapa access arr[i] dapat dilakukan dalam O(1)?",
      options: [
        { id: "address-formula", label: "Alamat elemen dihitung langsung dari base address dan index" },
        { id: "linear-scan", label: "Semua elemen sebelumnya selalu dipindai" },
        { id: "sorted", label: "Array selalu terurut" },
        { id: "linked", label: "Setiap elemen menyimpan pointer next" },
      ],
      correctOptionId: "address-formula",
      explanation: "Lokasi elemen dapat dihitung dari alamat awal ditambah offset index.",
    },
    {
      id: "array-update-identity",
      topicSlug: "update",
      prompt: "Apa yang terjadi pada identitas elemen saat nilainya diperbarui?",
      options: [
        { id: "preserved", label: "Identitas tetap, hanya nilai berubah" },
        { id: "recreated", label: "Seluruh Array dibuat ulang sebagai identitas baru" },
        { id: "deleted", label: "Elemen selalu dihapus dahulu" },
        { id: "shifted", label: "Semua elemen harus bergeser" },
      ],
      correctOptionId: "preserved",
      explanation: "Update mengganti nilai pada slot yang sama dan mempertahankan identitas logis elemen.",
    },
    {
      id: "array-traversal-order",
      topicSlug: "traversal",
      prompt: "Traversal Array berukuran n biasanya mengunjungi elemen dalam urutan...",
      options: [
        { id: "zero-to-n-minus-one", label: "0 hingga n - 1" },
        { id: "n-to-one", label: "n hingga 1" },
        { id: "random", label: "Acak" },
        { id: "middle-only", label: "Hanya index tengah" },
      ],
      correctOptionId: "zero-to-n-minus-one",
      explanation: "Traversal penuh mengunjungi setiap index dari 0 sampai n - 1 sehingga O(n).",
    },
    {
      id: "array-insert-shift-direction",
      topicSlug: "insert",
      prompt: "Saat insert di tengah Array, shifting yang aman dilakukan dari...",
      options: [
        { id: "right-to-left", label: "Kanan ke kiri" },
        { id: "left-to-right", label: "Kiri ke kanan" },
        { id: "middle-out", label: "Tengah ke dua arah" },
        { id: "no-shift", label: "Tidak perlu shifting" },
      ],
      correctOptionId: "right-to-left",
      explanation: "Pergeseran dari kanan ke kiri mencegah nilai sumber tertimpa sebelum disalin.",
    },
    {
      id: "array-delete-shift-direction",
      topicSlug: "delete",
      prompt: "Setelah elemen tengah dihapus, elemen di sebelah kanannya digeser...",
      options: [
        { id: "left", label: "Satu posisi ke kiri" },
        { id: "right", label: "Satu posisi ke kanan" },
        { id: "none", label: "Tidak bergerak" },
        { id: "random", label: "Ke posisi acak" },
      ],
      correctOptionId: "left",
      explanation: "Elemen setelah target bergeser ke kiri untuk menutup slot kosong.",
    },
    {
      id: "array-valid-insert-bound",
      topicSlug: "bounds",
      prompt: "Untuk Array dengan panjang 4, rentang index valid untuk insert adalah...",
      options: [
        { id: "zero-through-four", label: "0 sampai 4" },
        { id: "zero-through-three", label: "0 sampai 3" },
        { id: "one-through-four", label: "1 sampai 4" },
        { id: "only-four", label: "Hanya 4" },
      ],
      correctOptionId: "zero-through-four",
      explanation: "Insert menerima 0..length; index length berarti menambahkan di akhir.",
    },
    {
      id: "array-contiguous-address",
      topicSlug: "memory",
      prompt: "Jika integer berjarak 4 byte dan index 0 berada di 0xB100, alamat simulasi index 2 adalah...",
      options: [
        { id: "b108", label: "0xB108" },
        { id: "b102", label: "0xB102" },
        { id: "b104", label: "0xB104" },
        { id: "b120", label: "0xB120" },
      ],
      correctOptionId: "b108",
      explanation: "Index 2 memiliki offset 2 × 4 byte = 8 byte dari 0xB100.",
    },
    {
      id: "array-insert-complexity",
      topicSlug: "complexity",
      prompt: "Mengapa insert pada index umum dapat membutuhkan O(n)?",
      options: [
        { id: "shifting", label: "Sejumlah elemen mungkin harus digeser" },
        { id: "address-random", label: "Alamat Array selalu acak" },
        { id: "binary-search", label: "Insert selalu menjalankan binary search" },
        { id: "pointer-chain", label: "Harus mengikuti pointer next" },
      ],
      correctOptionId: "shifting",
      explanation: "Insert di depan atau tengah dapat menggeser hingga n elemen.",
    },
    {
      id: "array-versus-linked-list",
      topicSlug: "comparison",
      prompt: "Pernyataan yang tepat tentang Array dibanding Linked List adalah...",
      options: [
        { id: "contiguous-direct", label: "Array memakai lokasi kontigu dan mendukung akses index langsung" },
        { id: "next-pointer", label: "Setiap elemen Array wajib menyimpan pointer next" },
        { id: "no-index", label: "Array tidak memiliki index" },
        { id: "always-faster-insert", label: "Insert tengah Array selalu lebih cepat" },
      ],
      correctOptionId: "contiguous-direct",
      explanation: "Kontiguitas mendukung direct access, tetapi insert/delete tengah dapat memerlukan shifting.",
    },
  ],
});
