import { defineQuiz } from "@/features/quiz/definition";

export const linkedListQuiz = defineQuiz({
  moduleSlug: "linked-list",
  title: "Quiz Akhir Linked List",
  questions: [
    {
      id: "linked-list-node-parts",
      topicSlug: "node",
      prompt: "Dua bagian utama node pada Singly Linked List adalah…",
      options: [
        { id: "value-next", label: "value dan pointer next" },
        { id: "index-size", label: "index dan size" },
        { id: "key-parent", label: "key dan parent" },
        { id: "front-rear", label: "front dan rear" },
      ],
      correctOptionId: "value-next",
      explanation: "Node menyimpan data dan pointer next yang menghubungkannya ke node berikutnya.",
    },
    {
      id: "linked-list-head-role",
      topicSlug: "head",
      prompt: "Apa fungsi pointer HEAD?",
      options: [
        { id: "first-node", label: "Menunjuk node pertama" },
        { id: "last-node", label: "Selalu menunjuk node terakhir" },
        { id: "node-count", label: "Menyimpan jumlah node" },
        { id: "sort-list", label: "Mengurutkan seluruh list" },
      ],
      correctOptionId: "first-node",
      explanation: "HEAD adalah titik masuk list dan menunjuk node pertama, atau NULL bila list kosong.",
    },
    {
      id: "linked-list-null-meaning",
      topicSlug: "null",
      prompt: "Pada tail Singly Linked List, nilai next biasanya…",
      options: [
        { id: "head", label: "HEAD" },
        { id: "null", label: "NULL" },
        { id: "previous", label: "Node sebelumnya" },
        { id: "zero-value", label: "Nilai data 0" },
      ],
      correctOptionId: "null",
      explanation: "NULL pada next menandai bahwa tidak ada node berikutnya dan traversal selesai.",
    },
    {
      id: "linked-list-traversal-cost",
      topicSlug: "traversal",
      prompt: "Kompleksitas waktu traversal seluruh list dengan n node adalah…",
      options: [
        { id: "constant", label: "O(1)" },
        { id: "logarithmic", label: "O(log n)" },
        { id: "linear", label: "O(n)" },
        { id: "quadratic", label: "O(n²)" },
      ],
      correctOptionId: "linear",
      explanation: "Traversal mengikuti setiap pointer next sekali, sehingga waktunya linear terhadap jumlah node.",
    },
    {
      id: "linked-list-search-stop",
      topicSlug: "search",
      prompt: "Search yang tidak menemukan target berhenti ketika…",
      options: [
        { id: "value-zero", label: "Menemukan nilai 0" },
        { id: "next-null", label: "Pointer current mencapai NULL" },
        { id: "back-head", label: "Pointer kembali ke HEAD" },
        { id: "index-full", label: "Index sama dengan kapasitas array" },
      ],
      correctOptionId: "next-null",
      explanation: "Pada Singly Linked List non-siklik, NULL menandai akhir ruang pencarian.",
    },
    {
      id: "linked-list-insert-head-order",
      topicSlug: "insert-head",
      prompt: "Urutan pointer yang benar untuk Insert Head adalah…",
      options: [
        { id: "connect-then-head", label: "new.next = HEAD, lalu HEAD = new" },
        { id: "head-then-connect", label: "HEAD = new, lalu new.next = HEAD" },
        { id: "tail-then-head", label: "tail.next = new, lalu HEAD = NULL" },
        { id: "delete-then-create", label: "Hapus HEAD, lalu buat node baru" },
      ],
      correctOptionId: "connect-then-head",
      explanation: "Node baru harus mempertahankan akses ke HEAD lama sebelum HEAD dipindahkan.",
    },
    {
      id: "linked-list-insert-tail-need",
      topicSlug: "insert-tail",
      prompt: "Tanpa pointer tail khusus, Insert Tail perlu…",
      options: [
        { id: "traverse-tail", label: "Traversal hingga node terakhir" },
        { id: "binary-search", label: "Binary search pada node" },
        { id: "sort-first", label: "Mengurutkan list terlebih dahulu" },
        { id: "move-head", label: "Memindahkan HEAD ke NULL" },
      ],
      correctOptionId: "traverse-tail",
      explanation: "Kita harus mengikuti next dari HEAD hingga menemukan node dengan next NULL.",
    },
    {
      id: "linked-list-insert-position-links",
      topicSlug: "insert-position",
      prompt: "Saat menyisipkan di tengah list, pointer mana yang harus diperbarui?",
      options: [
        { id: "new-and-previous", label: "next node baru dan next predecessor" },
        { id: "head-only", label: "Hanya HEAD" },
        { id: "tail-only", label: "Hanya next pada tail" },
        { id: "all-values", label: "Semua value node" },
      ],
      correctOptionId: "new-and-previous",
      explanation: "Node baru menunjuk successor, lalu predecessor menunjuk node baru.",
    },
    {
      id: "linked-list-delete-middle",
      topicSlug: "deletion",
      prompt: "Sebelum menghapus node tengah, predecessor harus…",
      options: [
        { id: "skip-target", label: "Menunjuk successor dari target" },
        { id: "point-target", label: "Tetap menunjuk target selamanya" },
        { id: "become-null", label: "Selalu diubah menjadi NULL" },
        { id: "copy-value", label: "Menyalin value ke semua node" },
      ],
      correctOptionId: "skip-target",
      explanation: "Rewiring predecessor ke successor menjaga list tetap tersambung setelah target dilepas.",
    },
    {
      id: "linked-list-memory-tradeoff",
      topicSlug: "space-and-memory",
      prompt: "Dibanding array, setiap node Linked List memerlukan ruang tambahan untuk…",
      options: [
        { id: "next-pointer", label: "Pointer next" },
        { id: "fixed-index", label: "Index fisik tetap" },
        { id: "binary-tree", label: "Seluruh binary tree" },
        { id: "compiler", label: "Compiler C++" },
      ],
      correctOptionId: "next-pointer",
      explanation: "Fleksibilitas hubungan node dibayar dengan overhead penyimpanan pointer next.",
    },
  ],
});
