import { defineQuiz } from "@/features/quiz/definition";

export const stackQuiz = defineQuiz({
  moduleSlug: "stack",
  title: "Quiz Akhir Stack",
  questions: [
    {
      id: "stack-core-concept",
      topicSlug: "concept",
      prompt: "Stack adalah struktur data linear yang operasi utamanya berlangsung pada...",
      options: [
        { id: "one-end", label: "Satu ujung yang disebut TOP" },
        { id: "both-ends", label: "Kedua ujung secara bersamaan" },
        { id: "random", label: "Posisi acak" },
        { id: "middle", label: "Index tengah saja" },
      ],
      correctOptionId: "one-end",
      explanation: "Push, Pop, dan Peek bekerja pada satu ujung Stack, yaitu TOP.",
    },
    {
      id: "stack-lifo-order",
      topicSlug: "lifo",
      prompt: "Jika 10, 20, lalu 30 di-Push, nilai yang pertama kali di-Pop adalah...",
      options: [
        { id: "thirty", label: "30" },
        { id: "ten", label: "10" },
        { id: "twenty", label: "20" },
        { id: "none", label: "Tidak ada" },
      ],
      correctOptionId: "thirty",
      explanation: "LIFO berarti elemen terakhir masuk, 30, menjadi elemen pertama keluar.",
    },
    {
      id: "stack-top-empty",
      topicSlug: "top",
      prompt: "Dalam model Stack Array ini, nilai TOP saat Stack kosong adalah...",
      options: [
        { id: "minus-one", label: "-1" },
        { id: "zero", label: "0" },
        { id: "one", label: "1" },
        { id: "capacity", label: "kapasitas" },
      ],
      correctOptionId: "minus-one",
      explanation: "TOP diturunkan sebagai size - 1, sehingga Stack kosong memiliki TOP = -1.",
    },
    {
      id: "stack-push-effect",
      topicSlug: "push",
      prompt: "Apa efek Push yang berhasil pada Stack?",
      options: [
        { id: "append", label: "Menambah nilai di TOP dan menaikkan ukuran" },
        { id: "remove", label: "Menghapus nilai TOP" },
        { id: "read", label: "Hanya membaca nilai TOP" },
        { id: "clear", label: "Mengosongkan seluruh Stack" },
      ],
      correctOptionId: "append",
      explanation: "Push menempatkan elemen pada slot setelah TOP lama dan menambah ukuran satu.",
    },
    {
      id: "stack-pop-effect",
      topicSlug: "pop",
      prompt: "Operasi Pop mengembalikan dan menghapus...",
      options: [
        { id: "top", label: "Elemen TOP" },
        { id: "bottom", label: "Elemen BOTTOM" },
        { id: "all", label: "Semua elemen" },
        { id: "middle", label: "Elemen tengah" },
      ],
      correctOptionId: "top",
      explanation: "Sesuai LIFO, Pop hanya bekerja pada elemen TOP.",
    },
    {
      id: "stack-peek-mutation",
      topicSlug: "peek",
      prompt: "Pernyataan yang tepat tentang Peek adalah...",
      options: [
        { id: "read-only", label: "Membaca TOP tanpa mengubah Stack" },
        { id: "remove", label: "Membaca lalu menghapus TOP" },
        { id: "push", label: "Menambah elemen baru" },
        { id: "sort", label: "Mengurutkan seluruh elemen" },
      ],
      correctOptionId: "read-only",
      explanation: "Peek adalah operasi baca-saja; isi, ukuran, dan TOP tetap.",
    },
    {
      id: "stack-empty-check",
      topicSlug: "is-empty",
      prompt: "isEmpty menghasilkan true ketika...",
      options: [
        { id: "top-minus-one", label: "TOP = -1" },
        { id: "top-zero", label: "TOP = 0" },
        { id: "size-capacity", label: "ukuran = kapasitas" },
        { id: "duplicate", label: "ada nilai duplikat" },
      ],
      correctOptionId: "top-minus-one",
      explanation: "TOP = -1 menandakan tidak ada slot aktif pada Stack.",
    },
    {
      id: "stack-full-check",
      topicSlug: "is-full",
      prompt: "Stack berkapasitas 8 dianggap penuh ketika ukurannya...",
      options: [
        { id: "eight", label: "8" },
        { id: "seven", label: "7" },
        { id: "zero", label: "0" },
        { id: "nine", label: "9" },
      ],
      correctOptionId: "eight",
      explanation: "isFull bernilai true saat ukuran sama dengan kapasitas, yaitu 8.",
    },
    {
      id: "stack-boundary-errors",
      topicSlug: "overflow-underflow",
      prompt: "Pasangan kondisi yang benar adalah...",
      options: [
        { id: "push-full-pop-empty", label: "Push pada Stack penuh = overflow; Pop pada Stack kosong = underflow" },
        { id: "push-empty-pop-full", label: "Push pada Stack kosong = overflow; Pop pada Stack penuh = underflow" },
        { id: "both-overflow", label: "Keduanya selalu overflow" },
        { id: "never-error", label: "Keduanya tidak pernah gagal" },
      ],
      correctOptionId: "push-full-pop-empty",
      explanation: "Overflow terjadi saat menambah ke kapasitas penuh; underflow saat mengambil dari Stack kosong.",
    },
    {
      id: "stack-operation-complexity",
      topicSlug: "complexity",
      prompt: "Kompleksitas waktu Push, Pop, Peek, isEmpty, dan isFull adalah...",
      options: [
        { id: "constant", label: "O(1)" },
        { id: "linear", label: "O(n)" },
        { id: "logarithmic", label: "O(log n)" },
        { id: "quadratic", label: "O(n²)" },
      ],
      correctOptionId: "constant",
      explanation: "Semua operasi hanya membaca atau mengubah data pada TOP atau metadata ukuran secara langsung.",
    },
  ],
});
